CREATE DATABASE Filmes_tarde;
GO

USE Filmes_tarde;
GO

CREATE TABLE Generos(
	IdGenero	INT PRIMARY KEY IDENTITY
	,Nome		VARCHAR (255) NOT NULL UNIQUE
);
GO

CREATE TABLE Filmes(
	IdFilme		INT PRIMARY KEY IDENTITY
	,Titulo		VARCHAR (255) NOT NULL UNIQUE
	,IdGenero	INT FOREIGN KEY REFERENCES Generos (IdGenero)
);
GO

CREATE TABLE Permissao(
	IdPermissao		INT PRIMARY KEY IDENTITY
	,Comum			VARCHAR (255) NOT NULL UNIQUE
	,Administrador  VARCHAR (255) NOT NULL UNIQUE

);

CREATE TABLE Usuario(
	IdUsuario	INT PRIMARY KEY IDENTITY
	,Email		VARCHAR (255) NOT NULL UNIQUE
	,Senha		VARCHAR (255) NOT NULL
	,IdPermissao INT FOREIGN KEY REFERENCES Permissao(IdPermissao)
);
GO
